language: python

install: pip install -q .[tests_require]

cache: pip

script: make test

jobs:
  include:
    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
    - stage: code coverage
      python: 3.7
      dist: xenial
      sudo: true
      install: pip install coveralls
      script:
      - coverage run --source=botmaker setup.py test
      - coveralls
