language: python

install: make install-test

cache: pip

script:
  - make lint
  - python setup.py test

jobs:
  include:
    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
    - stage: code coverage
      python: 3.7
      dist: xenial
      sudo: true
      install:
        - make install-test
        - pip install coveralls
      script:
        - coverage run --source=botmaker setup.py test
        - coveralls
